POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "String",
  "password": "String"
}




###
PUT http://localhost:8080/auth/verification
Content-Type: application/json

{
  "phoneNumber": "String",
  "activationCode": "String"
}